# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [9]:
x = "The diameter of {planet} is {dia}".format(planet ="Earth",dia = 12742)
print(x)

The diameter of Earth is 12742


## 3. In this nest dictionary grab the word "hello"

In [10]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [38]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [28]:
import numpy as np


## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [29]:
array=np.zeros(10)

In [30]:
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
array=np.ones(10)*5
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [32]:
array=np.arange(20,35,2)

In [33]:
array

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [34]:
matrix=np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [36]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
ab=np.concatenate((a,b), axis=0)
ab

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [37]:
import pandas as pd


In [39]:
df = pd.DataFrame(np.random.randint(0,50,size=(3, 2)), columns=list('XY'))
df

X   Y
0  26  26
1  13  34
2   6  20

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [40]:
dt=pd.date_range(start='1-1-2023',end='10-2-2023',freq='5H')
dt

DatetimeIndex(['2023-01-01 00:00:00', '2023-01-01 05:00:00',
               '2023-01-01 10:00:00', '2023-01-01 15:00:00',
               '2023-01-01 20:00:00', '2023-01-02 01:00:00',
               '2023-01-02 06:00:00', '2023-01-02 11:00:00',
               '2023-01-02 16:00:00', '2023-01-02 21:00:00',
               ...
               '2023-09-30 02:00:00', '2023-09-30 07:00:00',
               '2023-09-30 12:00:00', '2023-09-30 17:00:00',
               '2023-09-30 22:00:00', '2023-10-01 03:00:00',
               '2023-10-01 08:00:00', '2023-10-01 13:00:00',
               '2023-10-01 18:00:00', '2023-10-01 23:00:00'],
              dtype='datetime64[ns]', length=1316, freq='5H')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [41]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=['sno','tag','num'])
df


sno  tag  num
0    1  aaa   22
1    2  bbb   25
2    3  ccc   24