# Basic Python

## 1. Split this string

In [4]:
s = "Hi there Sam!"

In [5]:
slist = s.split(" ")
for j in slist:
    print(j)

Hi
there
Sam!


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [7]:
planet = "Earth"
diameter = 12742

In [9]:
str1 = "The diameter of {planet_name} is {num} kilometers". format(planet_name = planet, num = diameter)
print(str1) 

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [10]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [11]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [12]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [13]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
arr1 = np.ones(10)*5
arr1

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [15]:
arr2 = np.arange(20,35,2)
arr2

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
arr3 = np.arange(0,9).reshape(3,3)
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [18]:
ab = np.concatenate((a, b))
ab

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [20]:
import pandas as pd


In [21]:
df = pd.DataFrame(np.random.randint(0,100,size=(3, 2)), columns=list('XY'))
df

X   Y
0   8  77
1  12   4
2  99  33

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [2]:
import pandas as pd 
date = pd.date_range(start ='1-1-2023', end ='5-10-2023', freq ='10D')
  
for val in date:
    print(val)

2023-01-01 00:00:00
2023-01-11 00:00:00
2023-01-21 00:00:00
2023-01-31 00:00:00
2023-02-10 00:00:00
2023-02-20 00:00:00
2023-03-02 00:00:00
2023-03-12 00:00:00
2023-03-22 00:00:00
2023-04-01 00:00:00
2023-04-11 00:00:00
2023-04-21 00:00:00
2023-05-01 00:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [22]:
list_1 = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [25]:
import pandas as pd
df = pd.DataFrame(list_1, columns =['No','String','Cnt']) 
print(df)

   No String  Cnt
0   1    aaa   22
1   2    bbb   25
2   3    ccc   24
